name: Magic Explosion
version: 0.2.1
main: com.skyost.me.MEPlugin
author: Skyost
website: http://www.imcbans.cu.cc/
permisions:
 magicexplosion.player.usefeather:
  default: op
  description: Allows you to use the feather for creating explosions